### ISSUE TITLE
Problem running ICA-AROMA

### ISSUE THREAD

**Issue by khazarAhmadi** [rhr-pruim/ICA-AROMA#70]
Hello, 

I have sub-millimeter task-based fMRI data (dimension = 256 x 340 x 280 x 256, voxel size = 0.75 mm, isotropic) that have been preprocessed using an in-house pipeline based on functions of ANTS, FSL and SPM. I ran ICA-AROMA to regress out motion estimates but it failed with the following error. 

python ICA_AROMA.py -in ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/LME/Run1-AP-dummyRemoved-sliceRemove_MoCorr_DistCorr_anatomyAligned.nii.gz -out ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/LME/AROMA -a ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/preprocess_output_complete/Run1-AP-dummyRemoved-sliceRemove_DistCorr_template0_fslBBR.mat -mc ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/preprocess_output_complete/Run1-AP-dummyRemoved-sliceRemove_MoCorr.params -m ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/preprocess_output_complete/Run1-AP-fixedMask-coregistered.nii.gz

Step 1) MELODIC
Killed
Traceback (most recent call last):
  File "ICA_AROMA.py", line 204, in <module>
    aromafunc.runICA(fslDir, inFile, outDir, melDir, mask, dim, TR)
  File "/home/kahmadi/ICA-AROMA/ICA_AROMA_functions.py", line 94, in runICA
    nrICs = int(float(subprocess.getoutput(cmd)))
ValueError: could not convert string to float: 'Image Exception : #63 :: No image files match: ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/LME/AROMA/melodic.ica/melodic_IC\nNo image files match: ../../../media/kahmadi/Elements1/DavidsData/20210727_P02_7035_S1_Struct/functional/LME/AROMA/melodic.ica/melodic_IC'

Since I'm interested to perform laminar analysis, I don't have warp files on MNI template registration. Could that be the reason for this error? Or is it due to RAM issues (I have an Ubuntu system with 65 G of memory and 14 CPU cores). I also have not run FEAT on this dataset. Any help would be greatly appreciated! 

Best, 
Khazar

**Comment by maartenmennes** [comment]
try running your command with the full paths specified, i.e., no ../../../ specifications. The error you're getting is related to AROMA not being able to locate your files.

Are your input files to AROMA in MNI152 2mm resolution? This will be needed, otherwise the masking needed for the classifier will not work. Note that you can run the classifier on MNI152 2mm data and then apply fsl_regfilt on your data in native space using the components derived from the MNI152 space analysis.
