### ISSUE TITLE
issue with requirements.txt

### ISSUE THREAD

**Issue by bokenge** [rhr-pruim/ICA-AROMA#73]
Hello,
I am trying to install requirements.txt and I am getting an error in the step "Collecting matplotlib==2.2".
It is showing exit code 1 when it reaches "Getting requirements to build wheel". Below is the output:
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      /private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-install-_cnrmugb/matplotlib_bd14727d895e46488127d0430c610713/setupext.py:2054: SyntaxWarning: invalid escape sequence '\.'
        pattern = '(3\.1\d+)|(MiKTeX \d+.\d+)'
      /private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-install-_cnrmugb/matplotlib_bd14727d895e46488127d0430c610713/versioneer.py:472: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      IMPORTANT WARNING:
          pkg-config is not installed.
          matplotlib may not be able to find some of its dependencies
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-build-env-lk4xs6bz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-build-env-lk4xs6bz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-build-env-lk4xs6bz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-build-env-lk4xs6bz/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 48, in <module>
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-install-_cnrmugb/matplotlib_bd14727d895e46488127d0430c610713/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-install-_cnrmugb/matplotlib_bd14727d895e46488127d0430c610713/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2d/brb9hgdj0s52_fyz8x_4ckd80000gq/T/pip-install-_cnrmugb/matplotlib_bd14727d895e46488127d0430c610713/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

What am i doing wrong? Thanks in advance for the help!

**Comment by maartenmennes** [comment]
Hi,
as an alternative to installing the requirements.txt, you can open the file and do a pip install of each listed module separately. That said, if you're running e.g., anaconda, chances are you're already good regarding the requirements...

**Comment by bokenge** [comment]
Hi, thanks for the help. When I try to pip install each module separately, two of them work, however the other three give me basically the same error output:

 AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      IMPORTANT WARNING:
          pkg-config is not installed.
          matplotlib may not be able to find some of its dependencies

**Comment by bokenge** [comment]
I was able to install pkg-config which removed the warning when I ran it again, however the AttibuteError is still showing the same

**Comment by maartenmennes** [comment]
the required libraries are not exotic ones, are you running a non-standard python?

**Comment by bokenge** [comment]
No, I am using python 3.12
Again, thanks for the help. I'm very confused!
